server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"




# 数据库连接配置
database:
  logger:
    path:    "temp/logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    # link:   "mysql:root:12345678@tcp(127.0.0.1:3306)/focus"
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/shop"
    debug:  true



# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:      1
    pass:        123456
    idleTimeout: 600

qiniu:
  bucket: "jk-test-1"
  accessKey: "GQHd76KVY85frjUn52T6n4lKX_KW5EekcGmJaDy_"
  secretKey: "pirtUMRnkm06c_mTQV0uc-IvE7Fa-Hm-d4OcKANg"
  url: "http://rtvkf3dlr.bkt.clouddn.com/"

upload:
  path: "upload"