// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "jk-goframe-shop/internal/logic/acticle"
	_ "jk-goframe-shop/internal/logic/admin"
	_ "jk-goframe-shop/internal/logic/bizctx"
	_ "jk-goframe-shop/internal/logic/category"
	_ "jk-goframe-shop/internal/logic/collection"
	_ "jk-goframe-shop/internal/logic/comment"
	_ "jk-goframe-shop/internal/logic/conpon"
	_ "jk-goframe-shop/internal/logic/file"
	_ "jk-goframe-shop/internal/logic/goods"
	_ "jk-goframe-shop/internal/logic/goods_options"
	_ "jk-goframe-shop/internal/logic/login"
	_ "jk-goframe-shop/internal/logic/middleware"
	_ "jk-goframe-shop/internal/logic/order"
	_ "jk-goframe-shop/internal/logic/permission"
	_ "jk-goframe-shop/internal/logic/position"
	_ "jk-goframe-shop/internal/logic/praise"
	_ "jk-goframe-shop/internal/logic/role"
	_ "jk-goframe-shop/internal/logic/rotation"
	_ "jk-goframe-shop/internal/logic/session"
	_ "jk-goframe-shop/internal/logic/user"
	_ "jk-goframe-shop/internal/logic/user_coupon"
	_ "jk-goframe-shop/internal/logic/video"
)
