// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// VideoInfo is the golang structure of table video_info for DAO operations like Where/Data.
type VideoInfo struct {
	g.Meta    `orm:"table:video_info, do:true"`
	Id        interface{} // 视频id
	Type      interface{} // 视频所属的类型
	Title     interface{} // 视频的标题
	Sticky    interface{} // 视频属于哪个topBar
	Url       interface{} // 视频的链接
	Cover     interface{} // 视频的封面图片链接
	View      interface{} // 播放次数
	Duration  interface{} // 播放时长
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
