// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"jk-goframe-shop/internal/model"
)

type (
	IPraise interface {
		AddPraise(ctx context.Context, in model.PraiseAddInput) (res *model.PraiseAddOutput, err error)
		DeletePraise(ctx context.Context, in model.PraiseDeleteInput) (res *model.PraiseDeleteOutput, err error)
		GetList(ctx context.Context, in model.PraiseGetListInput) (out *model.PraiseGetListOutput, err error)
	}
)

var (
	localPraise IPraise
)

func Praise() IPraise {
	if localPraise == nil {
		panic("implement not found for interface IPraise, forgot register?")
	}
	return localPraise
}

func RegisterPraise(i IPraise) {
	localPraise = i
}
