// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jk-goframe-shop/internal/dao/internal"
)

// internalVideoInfoDao is internal type for wrapping internal DAO implements.
type internalVideoInfoDao = *internal.VideoInfoDao

// videoInfoDao is the data access object for table video_info.
// You can define custom methods on it to extend its functionality as you wish.
type videoInfoDao struct {
	internalVideoInfoDao
}

var (
	// VideoInfo is globally public accessible object for table video_info operations.
	VideoInfo = videoInfoDao{
		internal.NewVideoInfoDao(),
	}
)

// Fill with you ideas below.
