// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VideoInfo is the golang structure for table video_info.
type VideoInfo struct {
	Id        int         `json:"id"        description:"视频id"`
	Type      int         `json:"type"      description:"视频所属的类型"`
	Title     string      `json:"title"     description:"视频的标题"`
	Sticky    int         `json:"sticky"    description:"视频属于哪个topBar"`
	Url       string      `json:"url"       description:"视频的链接"`
	Cover     string      `json:"cover"     description:"视频的封面图片链接"`
	View      int         `json:"view"      description:"播放次数"`
	Duration  int         `json:"duration"  description:"播放时长"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
